class ${1:Name}Error(${2:Exception}): pass
